### ISSUE TITLE
create_dagrun doesn't seem to work when called from scheduler in airflow 2.0

### ISSUE THREAD

**Issue by knxacgcg** [OpenLineage/OpenLineage#126] opened 2021-07-30 23:42 UTC
https://github.com/OpenLineage/OpenLineage/blob/0a6be73d855e9bd5e1c61453190343b17ca1082d/integration/airflow/openlineage/airflow/dag.py#L102

# Dependencies:
Airflow Version: 2.1.2
Python Version: 3.8.0
OpenLineage Library Versions:
* git+https://github.com/OpenLineage/OpenLineage.git@47fdac36d32f607e611e4f7838637e294929518f#egg=openlineage-python&subdirectory=client/python
* git+https://github.com/OpenLineage/OpenLineage.git@47fdac36d32f607e611e4f7838637e294929518f#egg=openlineage-integration-common&subdirectory=integration/common
* git+https://github.com/OpenLineage/OpenLineage.git@47fdac36d32f607e611e4f7838637e294929518f#egg=openlineage-airflow&subdirectory=integration/airflow

# Sample DAG:
```python
from datetime import datetime

from openlineage.airflow import DAG
from airflow.operators.bash import BashOperator
import http
http.client.HTTPConnection.debuglevel = 1

airflow_defaults = {"owner": "test-airflow", "start_date": datetime(2020, 8, 19)}
dag = DAG(
    "sample_run_1",
    default_args=airflow_defaults,
    catchup=False,
    schedule_interval="* * * * *"
)

with dag:
    bash_task = BashOperator(
        task_id="bash_task",
        bash_command=""" echo "${OPENLINEAGE_URL} | ${OPENLINEAGE_PRODUCER} |  ${OPENLINEAGE_API_KEY} | ${OPENLINEAGE_NAMESPACE}" """
    )
```

# Runs
1. Running via Interpreter:
when running directly through a python script, the openlineage override create_dagrun seems to work correctly and has the correct type. it also properly emits to the openlineage endpoint
```python
from airflow.utils.types import DagRunType
from airflow.utils.state import State
from datetime import datetime
from airflow.utils import timezone

dag.create_dagrun(state=State.QUEUED, run_type=DagRunType.MANUAL, execution_date=timezone.make_aware(datetime.now()))
```
```bash
[2021-07-30 16:28:28,412] {dag.py:103} INFO - **** STARTING CREATE DAGRUN OPENLINEAGE ******
[2021-07-30 16:28:28,413] {dag.py:1770} INFO - **** STARTING CREATE DAGRUN ******
[2021-07-30 16:28:28,413] {dag.py:1771} INFO - <DAG: sample_run_1>. <class 'openlineage.airflow.dag.DAG'>
```

2. Running via Scheduler:
however, when triggered from the scheduler / ui, it appears to only run the native create_dagrun method and nothing is emitted to the openlineage endpoint
```bash
[2021-07-30 16:29:02,426] {dag.py:1770} INFO - **** STARTING CREATE DAGRUN ******
[2021-07-30 16:29:02,426] {dag.py:1771} INFO - <DAG: sample_run_1>. <class 'airflow.serialization.serialized_objects.SerializedDAG'>
```

# How to reproduce:
* create a log entry ( or debug breakpoint ) within openlineage.airflow.dag.DAG.create_dagrun and airflow.models.dag.DAG.create_dagrun
* run a dag that uses openlineage.airflow.DAG
* check if both log entries appear, or if only the log entry from airflow.models.dag.DAG.create_dagrun is emitted. additionally, there will be no request made to the OPENLINEAGE_URL endpoint

**Comment by mobuchowski** [comment] 2021-08-02 09:33
Hey @knxacgcg, thanks for reporting this issue. We're aware of this behavior, apparently caused by this PR: https://github.com/apache/airflow/pull/10956

We're thinking about the potential solutions, one of which could be working through current Airflow lineage decorators.

**Comment by knxacgcg** [comment] 2021-08-03 18:55
@mobuchowski . I see - does that mean overrides to the DAG class is no longer a viable option?
is there any current workaround to make this work in airflow 2?

**Comment by mobuchowski** [comment] 2021-08-06 12:47
@knxacgcg I don't believe there is any simple workaround.

**Comment by mobuchowski** [comment] 2021-09-30 16:26
Will be fixed by Airflow 2 support here: https://github.com/OpenLineage/OpenLineage/issues/205

**Closed by mobuchowski** 2021-09-30 16:26 UTC
