### ISSUE TITLE
airflow: using Openlineage 0.8.2 against Airflow 2.3.2 results in plugin import error

### ISSUE THREAD

**Issue by howardyoo** [OpenLineage/OpenLineage#872] opened 2022-06-22 17:39 UTC
How to reproduce:
- use OpenLineage 0.8.2 with Airflow 2.3.2
- The following error is observed:
![image](https://user-images.githubusercontent.com/32691630/175101397-59113917-532f-407b-a90c-049027347245.png)

**Comment by howardyoo** [comment] 2022-07-21 14:44
Hi Maciej, do we know the reason for this error?
We did see similar errors related to loading plugins - I wonder if there is a way to make logging better to reveal cause of this better.

**Comment by mobuchowski** [comment] 2022-07-21 16:37
@howardyoo 

Most likely cause of failure here is cyclic imports, caused by using something from Airflow.

I guess the fix for this will be some page in the docs and logs that will mention in FULL CAPS to not import anything from Airflow at top level?

**Comment by howardyoo** [comment] 2022-07-21 16:45
> @howardyoo
> 
> Most likely cause of failure here is cyclic imports, caused by using something from Airflow.
> 
> I guess the fix for this will be some page in the docs and logs that will mention in FULL CAPS to not import anything from Airflow at top level?

I am +1 on that idea, to have section in troubleshooting in our docs - to cover problems like this.

**Closed** 2022-07-29 15:29 UTC
Labels: bug, integration/airflow
