### ISSUE TITLE
spark: fix flaky testInsertIntoDataSourceDirVisitor

### ISSUE THREAD

**Issue by mobuchowski** [OpenLineage/OpenLineage#962] opened 2022-07-28 16:05 UTC
This test intermittently fails: like https://app.circleci.com/pipelines/github/OpenLineage/OpenLineage/4205/workflows/ea5d2d2a-8610-4e76-9c2e-b884ca36d7e1/jobs/47607

**Comment by pawel-big-lebowski** [comment] 2022-08-09 14:21
Duplicate of https://github.com/OpenLineage/OpenLineage/issues/999
found that too late, sry

**Closed by pawel-big-lebowski** 2022-08-09 14:21 UTC
Labels: integration/spark
