### ISSUE TITLE
The SQL Extractor in Airflow fails to take into account split_statement operator parameter

### ISSUE THREAD

**Issue by alescervenka** [OpenLineage/OpenLineage#1827] opened 2023-05-05 02:51 UTC
I am using the SQLExecuteQueryOperator in Airflow to run SQL in a PostgreSQL database. The corresponding SQL Extractor from OpenLineage fails to parse these three statements:

**ALTER SEQUENCE tablename RESTART WITH 1;**
The error message is _Expected one of TABLE or INDEX, found: SEQUENCE_

**ANALYZE tablename;**
The error message indicates that ANALYZE needs to be followed by TABLE. That modification, however, would not be accepted by the database engine.

**TRUNCATE tablename;**
Again, the error message indicates that TRUNCATE needs to be followed by the TABLE keyword. That is not strictly necessary in PostgreSQL.

**Comment by mobuchowski** [comment] 2023-05-18 12:44
@alescervenka this generally should create error facet, but not prevent parsing of other SQL statements, or otherwise, in the case of first two statements, generate useful lineage information, right?

I think `TRUNCATE tablename;` should work though, and will look on that

**Comment by mobuchowski** [comment] 2023-05-22 13:31
`TRUNCATE` should be fixed in the next release https://github.com/sqlparser-rs/sqlparser-rs/pull/883

**Comment by alescervenka** [comment] 2023-05-23 11:35
Thank you for fixing the TRUNCATE @mobuchowski . 

I tried testing you hypothesis that the two issues might not prevent the extractor from generating a useful lineage. I did that in a DAG with operator:

```
update_table = SQLExecuteQueryOperator(
    task_id='update_table',
    conn_id = PG,
    autocommit = True,
    sql = """ANALYZE stage.source_table;
    update stage.source_table set cvalue = 'there' where ckey = 'where';
    """,
    split_statements = True,
    dag = dag
)
```

When I check the result of extraction in Marquez (at http://localhost:3000/lineage/job/default/sql_lineage_test.update_table), I can see the extraction facet in the resulting JSON but no lineage information in the graph above:
![screenshot-20230523-133251](https://github.com/OpenLineage/OpenLineage/assets/25899548/189c369f-6bf7-4ced-bb9f-5d3b86f0ec80)

**Comment by mobuchowski** [comment] 2023-05-23 12:00
@alescervenka I believe this is a bug - but a different one, related to not properly handling `split_statements`, rather than parser. Parser does right thing when I pass it a list of statements instead of single one. I'll change title of this issue to reflect where the problem is.

<img width="1068" alt="Screenshot 2023-05-23 at 13 53 48" src="https://github.com/OpenLineage/OpenLineage/assets/6503007/b3517e64-613b-4da0-8c1d-79f980c19f8b">

**Closed** 2024-09-20 19:22 UTC
Labels: kind:bug, area:integration/airflow
