### ISSUE TITLE
Flink with Kafka

### ISSUE THREAD

**Issue by waytoharish** [OpenLineage/OpenLineage#2840] opened 2024-07-09 18:30 UTC
### What kind of integration is this?

- [x] Produces OpenLineage metadata
- [x] Consumes OpenLineage metadata
- [ ] Something else

### How should this integration be implemented?

I am trying to integrate the Flink using Kafka but openLinage client is not working.
Here is the Code

package io.openlineage.flink;

import io.openlineage.client.OpenLineageClient;
import io.openlineage.client.transports.HttpConfig;
import io.openlineage.client.transports.HttpTransport;
import io.openlineage.flink.avro.event.InputEvent;
import io.openlineage.flink.avro.event.OutputEvent;
import io.openlineage.util.EnvUtils;
import io.openlineage.util.OpenLineageFlinkJobListenerBuilder;
import org.apache.flink.streaming.api.environment.StreamExecutionEnvironment;
import org.apache.flink.types.Row;

import java.net.URI;

import static io.openlineage.flink.StreamEnvironment.setupEnv;
import static io.openlineage.kafka.SinkAndSourceClientProvider.*;
import static org.apache.flink.api.common.eventtime.WatermarkStrategy.noWatermarks;

public class FromKafkaToKafkaTopicApplication {
    public static void main(String[] args) throws Exception {

        HttpConfig httpConfig = new HttpConfig();
        httpConfig.setUrl(URI.create("http://localhost:5000"));

        OpenLineageClient client = OpenLineageClient.builder()
                .transport(
                        new HttpTransport(httpConfig))
                .build();

        EnvUtils.waitForSchemaRegistry();
        StreamExecutionEnvironment env = setupEnv(args);

        env.fromSource(
                        aKafkaSource("io.openlineage.flink.kafka.input.*"),
                        noWatermarks(),
                        "kafka-source")
                .uid("kafka-source")
                .keyBy(InputEvent::getId)
                .process(new StatefulCounter())
                .name("process")
                .uid("process")
                .map(outputEvent -> new OutputEvent(
                        outputEvent.id, outputEvent.version, outputEvent.counter

                ))
                .sinkTo(aKafkaSink("io.openlineage.flink.kafka.output"))
                .name("kafka-sink")
                .uid("kafka-sink");

        // OpenLineage specific code
        env.registerJobListener(
                OpenLineageFlinkJobListenerBuilder
                        .create()
                        .executionEnvironment(env)
                        .jobName("from-topic-to-psql")
                        .build()
        );

        env.execute("from-topic-to-psql");
    }

}

### Where should this integration be implemented?

- [ ] In the target system
- [ ] In the OpenLineage repo
- [ ] Somewhere else

### Do you plan to make this contribution yourself?

- [ ] I am interested in doing this work

**Comment by kacpermuda** [comment] 2024-07-10 07:09
Hey @waytoharish , could you provide more details on the issue: what error are you getting and provide some logs ? Thanks !

**Comment by waytoharish** [comment] 2024-07-10 07:11
HI @kacpermuda  Please can you confirm if this is right configuration as I not mapped OpenLineageClient anywhere in my code.

**Comment by pawel-big-lebowski** [comment] 2024-07-10 12:21
@waytoharish Could you verify if there are any events incoming into Marquez? There is lineage-events tab on the left on Marquez UI. Do you have any OpenLineage related logs on the Flink job side?

**Comment by waytoharish** [comment] 2024-07-13 10:06
Hi @pawel-big-lebowski This is what I am getting when running the application

2024-07-13 15:32:22,436 INFO  [flink-pekko.actor.default-dispatcher-8] executiongraph.ExecutionGraph (Execution.java:transitionState(1442)) - process -> Map -> kafka-sink: Writer -> kafka-sink: Committer (1/1) (bf04058142b62d71133a348ca64f15f7_4cd5c9eb987d451c700e0079a82c6902_0_0) switched from DEPLOYING to INITIALIZING.
Exception in thread "main" java.lang.NoSuchMethodError: 'io.openlineage.client.OpenLineageYaml io.openlineage.client.OpenLineageClientUtils.loadOpenLineageYaml(java.io.InputStream)'
	at io.openlineage.flink.client.FlinkConfigParser.parse(FlinkConfigParser.java:71)
	at io.openlineage.flink.visitor.lifecycle.FlinkExecutionContextFactory.getContext(FlinkExecutionContextFactory.java:29)
	at io.openlineage.flink.OpenLineageFlinkJobListener.start(OpenLineageFlinkJobListener.java:171)
	at io.openlineage.flink.OpenLineageFlinkJobListener.onJobSubmitted(OpenLineageFlinkJobListener.java:156)
	at org.apache.flink.streaming.api.environment.StreamExecutionEnvironment.lambda$executeAsync$15(StreamExecutionEnvironment.java:2242)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at org.apache.flink.streaming.api.environment.StreamExecutionEnvironment.executeAsync(StreamExecutionEnvironment.java:2242)
	at org.apache.flink.streaming.api.environment.StreamExecutionEnvironment.execute(StreamExecutionEnvironment.java:2125)
	at org.apache.flink.streaming.api.environment.LocalStreamEnvironment.execute(LocalStreamEnvironment.java:68)
	at org.apache.flink.streaming.api.environment.StreamExecutionEnvironment.execute(StreamExecutionEnvironment.java:2099)
	at io.openlineage.flink.FromKafkaToKafkaTopicApplication.main(FromKafkaToKafkaTopicApplication.java:58)

**Comment by waytoharish** [comment] 2024-07-15 04:39
@pawel-big-lebowski Please can you help here or redirect to someone else

**Comment by pawel-big-lebowski** [comment] 2024-07-16 08:24
Thanks @waytoharish for bringing the logs. 
```
Exception in thread "main" java.lang.NoSuchMethodError: 'io.openlineage.client.OpenLineageYaml io.openlineage.client.OpenLineageClientUtils.loadOpenLineageYaml(java.io.InputStream)'
```
This looks like some shading issue. To clarify first: what Flink version are you using and what version of openlineage-flink have you installed?

**Comment by waytoharish** [comment] 2024-07-16 09:00
@pawel-big-lebowski I am using Flink  flinkVersion = "1.18.1" and openlineage-flink 1.10.2 and openlineage-java:1.18.0. This is  same code working when run Flink with Docker but failing when running Flink as standalone jar.

**Comment by pawel-big-lebowski** [comment] 2024-07-16 10:32
>  openlineage-flink 1.10.2 and openlineage-java:1.18.0. 

This may be the cause. `openlineage-flink` already contains openlineage-java. Providing it independently in different versions can lead to such error. Please try more recent openlineage-flink  without adding openlineage-java.

**Comment by waytoharish** [comment] 2024-07-16 10:45
@pawel-big-lebowski Thanks. Let me update. is it fine to add following code ??

  HttpConfig httpConfig = new HttpConfig();
        httpConfig.setUrl(URI.create("http://3.226.254.222:5001"));
        OpenLineageClient.builder()
                .transport(
                        new HttpTransport(httpConfig))
                .build();

**Comment by waytoharish** [comment] 2024-07-16 11:04
@pawel-big-lebowski Still see this issue

2024-07-16 16:33:21,796 ERROR [main] flink.OpenLineageFlinkJobListener (OpenLineageFlinkJobListener.java:onJobSubmitted(158)) - Failed to notify OpenLineage about start
io.openlineage.client.OpenLineageClientException: No OpenLineage configuration file found
	at io.openlineage.client.OpenLineageClientUtils.loadOpenLineageYaml(OpenLineageClientUtils.java:215)
	at io.openlineage.client.Clients.newClient(Clients.java:29)
	at io.openlineage.client.Clients.newClient(Clients.java:20)
	at io.openlineage.flink.client.EventEmitter.<init>(EventEmitter.java:42)
	at io.openlineage.flink.visitor.lifecycle.FlinkExecutionContextFactory.getContext(FlinkExecutionContextFactory.java:38)
	at io.openlineage.flink.OpenLineageFlinkJobListener.start(OpenLineageFlinkJobListener.java:171)
	at io.openlineage.flink.OpenLineageFlinkJobListener.onJobSubmitted(OpenLineageFlinkJobListener.java:156)
	at org.apache.flink.streaming.api.environment.StreamExecutionEnvironment.lambda$executeAsync$15(StreamExecutionEnvironment.java:2242)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at org.apache.flink.streaming.api.environment.StreamExecutionEnvironment.executeAsync(StreamExecutionEnvironment.java:2242)
	at org.apache.flink.streaming.api.environment.StreamExecutionEnvironment.execute(StreamExecutionEnvironment.java:2125)
	at org.apache.flink.streaming.api.environment.LocalStreamEnvironment.execute(LocalStreamEnvironment.java:68)
	at org.apache.flink.streaming.api.environment.StreamExecutionEnvironment.execute(StreamExecutionEnvironment.java:2099)
	at io.openlineage.flink.FromKafkaToKafkaTopicApplication.main(FromKafkaToKafkaTopicApplication.java:58)

**Comment by pawel-big-lebowski** [comment] 2024-07-16 11:24
@waytoharish This is totally different issue. `No OpenLineage configuration file found`. How do you provide configuration: with `openlineage.yml` file or by Flink configuration settings? 

We're never testing scenario when there's no config yaml file provided, which may be the case here as well.

**Comment by waytoharish** [comment] 2024-07-16 11:51
@pawel-big-lebowski there is Java Code mentioned here I have used in my Job to configure 

https://openlineage.io/docs/integrations/flink

**Comment by pawel-big-lebowski** [comment] 2024-07-17 06:57
You should use yaml config file or Flink Conf, like described here -> https://openlineage.io/docs/integrations/flink/#configuring-openlineage-connector. Instantiating client on your own will not work.

**Comment by waytoharish** [comment] 2024-07-18 13:21
Thanks @pawel-big-lebowski it worked well not . Thanks a lot

**Comment by pawel-big-lebowski** [comment] 2024-07-19 07:34
@waytoharish Great to hear that. Can we close the issue?

**Closed** 2024-08-02 09:56 UTC
Labels: state:needs-triage
