### ISSUE TITLE
airflow: schemaURL missing in open lineage json message

### ISSUE THREAD

**Issue by cerveada** [OpenLineage/OpenLineage#702] opened 2022-04-25 14:41 UTC
According to specification `schemaURL` is mandatory field of RunEvent, but airflow integration sends a json messgaes without it.

Tested on
integration/airflow 0.7.1
Airflow 2.2.4

**Comment by kacpermuda** [comment] 2024-05-24 10:49
I was not able to reproduce this for latest version of OpenLineage, the `schemaUrl` is always present. Closing it for now, feel free to reopen if this issue persists.

**Closed by kacpermuda** 2024-05-24 10:49 UTC
Labels: kind:bug, area:integration/airflow
